#!/bin/bash

LANG=C

cpu="$1"

# determine actual governor
actual_gov=`cpupower -c $cpu frequency-info -p | sed -n '/governor/s@.*"\([[:alpha:]]\+\)".*@\1@p'`

# determine available governors
avail_gov=`cpupower -c $cpu frequency-info -g | sed -n '/available/s@.*: @@p'`

avail_gov1=`echo $avail_gov | sed "s/.*$actual_gov//"`
avail_gov2=`echo $avail_gov | sed "s/$actual_gov.*//"`
avail_gov=`echo "$avail_gov1 $avail_gov2" | sed "s/^\ //"`

next_gov=`echo $avail_gov | sed "s/\ .*//"`

cpupower -c $cpu frequency-set -g $next_gov
